typedef sequence<string> StringSeq;
module Data {
    interface Array {
        short reverseStrings(in StringSeq stringArray,
                             out StringSeq stringReversedArray);
    };
};
